"""Agent-Lite runtime package (S31+). Spec: docs/ROADMAP-agentlite.md."""

from .contracts import (
    FINISH_REASONS,
    VALID_ROLES,
    ModelMessage,
    ModelRequest,
    ModelResponse,
    ToolCall,
    ToolDefinition,
    ToolResult,
    knowledge_tool_definitions,
)
from .providers import (
    FakeModelProvider,
    ModelProvider,
    OllamaProvider,
    ProviderError,
)
from .registry import (
    EXECUTION,
    DESTRUCTIVE,
    EXTERNAL,
    READ_ONLY,
    SAFE_WRITE,
    VALID_SIDE_EFFECT_LEVELS,
    ALLOW_ALL_POLICY,
    PermissionPolicy,
    RegisteredTool,
    RegistryError,
    ToolRegistry,
    default_knowledge_registry,
    validate_tool_arguments,
)
from .session import (
    TERMINAL_STATES,
    AgentConfig,
    AgentSession,
    AgentState,
    SessionError,
)
from .workspace import (
    ProjectMetadata,
    PathError,
    PathPolicy,
    Workspace,
    WorkspaceConfig,
    WorkspaceError,
    WorkspaceManager,
)

__all__ = [
    "FINISH_REASONS",
    "VALID_ROLES",
    "ModelMessage",
    "ModelRequest",
    "ModelResponse",
    "ToolCall",
    "ToolDefinition",
    "ToolResult",
    "knowledge_tool_definitions",
    "FakeModelProvider",
    "ModelProvider",
    "OllamaProvider",
    "ProviderError",
    "TERMINAL_STATES",
    "AgentConfig",
    "AgentSession",
    "AgentState",
    "SessionError",
    "EXECUTION",
    "DESTRUCTIVE",
    "EXTERNAL",
    "READ_ONLY",
    "SAFE_WRITE",
    "VALID_SIDE_EFFECT_LEVELS",
    "ALLOW_ALL_POLICY",
    "PermissionPolicy",
    "RegisteredTool",
    "RegistryError",
    "ToolRegistry",
    "default_knowledge_registry",
    "validate_tool_arguments",
    "ProjectMetadata",
    "PathError",
    "PathPolicy",
    "Workspace",
    "WorkspaceConfig",
    "WorkspaceError",
    "WorkspaceManager",
]
